<a href="https://colab.research.google.com/github/HarshaR99/Colab_python/blob/master/NumPy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

[https://www.youtube.com/watch?v=QUT1VHiLmmI&t=2600s](https://)

Followed this course for NumPy

---



Initialising an array

In [6]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


Get number of dimensions

In [0]:
a.ndim

2

Get shape of (vector?)

In [0]:
a.shape

(2, 3)

Get datatype and to initialze array of desired datasize

In [0]:
# Get dtype of Numpy array
a.dtype
# initialzie array of required size
b = np.array([1,2,3],dtype = 'int16')

Get number of bytes of 1 item .

In [0]:
# int16 hence 2 bytes
b.itemsize

2

get size of array and total size

In [0]:
print('b.size:',b.size)
# now for totalsize
print('b.size * b.itemsize:',b.size * b.itemsize)
print('b.nbytes:',b.nbytes)

b.size: 3
b.size * b.itemsize: 6
b.nbytes: 6


# Initializsing different types of arrays

In [3]:
# All zeros matrix
# Takes shape as parameter
zero_mat = np.zeros((2,3,1))  # two pairs of parantheses ?
print(zero_mat)

[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]]


Explanation of structure of np array from outside to deepest nested state :

1.   [ [x], [x] ] the will "2" arrays nested in outermost array 
2.   x-> [ [y], [y], [y] ] where there are "3" arrays nested in   array x
3. y->[0] there is one array containing a zero in array y

2 -> 3 -> 1







In [0]:
# All one's matrix
ones_mat = np.ones((3,2,1),dtype = 'int16') # can also specify datatype
print(ones_mat)

[[[1]
  [1]]

 [[1]
  [1]]

 [[1]
  [1]]]


In [4]:
# A matrix filled with any other number
any_mat = np.full((2,2),7)
print(any_mat)

[[7 7]
 [7 7]]


In [0]:
np.ones((2,1))

array([[1.],
       [1.]])

In [0]:
# full_like
c = np.full_like(a,4)
print(c)
np.full(a.shape,3)

[[4 4 4]
 [4 4 4]]


array([[3, 3, 3],
       [3, 3, 3]])

Initialising random decimal values in matrix

Random values of shape passed as parameter

In [0]:
np.random.rand(3,1)

array([[0.61484068],
       [0.64927894],
       [0.33398093]])

In [7]:
np.random.random_sample(a.shape) 

array([[0.48139654, 0.16507196, 0.31757702],
       [0.01738777, 0.52937616, 0.77942752]])

Random integer values

In [0]:
# has integers between 0-7
np.random.randint(7,size = (2,3))

array([[6, 2, 5],
       [3, 2, 3]])

In [0]:
# random integer values between a certain range
np.random.randint(2,4,size = (1,3))

array([[2, 2, 3]])

In [0]:
# getting the identity matrix of desired size
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])