<a href="https://colab.research.google.com/github/HarshaR99/Colab_python/blob/master/NumPy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

[https://www.sharpsightlabs.com/blog/numpy-axes-explained/](https://)

This article has a good explanation for understading axes for 1-D and 2-D NumPy arrays

---



While copying numpy array maintain caution as you are assigning pointer to the new numpy array variable. Any change in one varibale will reflect in the other variable.

---


Hence use the copy() function

In [0]:
  a = np.array([1,2,3])
  b = a
  b[0] = 100
  print(a)

[100   2   3]


In [0]:
# how to avoid the mistake
a = np.array([1,2,3])
b = a.copy()             # copy function 
b[0] = 100
print(a)

[1 2 3]


Performing mathematical operations 

In [0]:
m = np.array([1,2,3])

In [0]:
m = m -2
print(m)

[-1  0  1]


In [0]:
m *= 2
print(m)

[-2  0  2]


In [0]:
# Trignometric operations
np.sin(m)        # radians ?

array([-0.90929743,  0.        ,  0.90929743])

#Linear Algerba

In [0]:
# matrix muliplication
a = np.ones((3,2))
b = np.full((2,3),2)
np.matmul(a,b)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [0]:
# Find the determinent 
c = np.identity(3)
np.linalg.det(c)

1.0

There are many more operations like  *trace ,eigen values,inverse*  that can be done which can be referred from the documentation.

#Statistics

In [0]:
stats = np.array([[1,2,3],[4,5,6]])

In [0]:
# to find minimum
np.min(stats)

1

In [0]:
# to find maximum along an axis
np.max(stats,axis = 1)

array([3, 6])

In [0]:
# to calculate sum
print(np.sum(stats))
print(np.sum(stats,axis=0))

21
[5 7 9]


#Restructuring NumPy Arrays

In [0]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)
after = before.reshape((2,2,2))
print(after)

(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [0]:
# Vertically Stacking Arrays
# all the input array dimensions for the concatenation axis must match exactly
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack([v1,v2])
# can also do vertical stack

array([[1, 2, 3],
       [4, 5, 6]])

In [1]:
# do no have any data set as of now yet
np.genfromtxt('data.txt',delimiter=',')

NameError: ignored